generatorName: python
packageName: allure_testops_client
library: asyncio
inputSpec: openapi/allure-testops-service/filtered-report-service.json
outputDir: src/client/generated
additionalProperties:
  packageName: allure_testops_client
  projectName: allure-testops-client
  generateSourceCodeOnly: true
  usePydanticV2: true
